---
- name: build mintsns-web image => {{role_path}}/docker/
  docker_image: 
    path: "{{role_path}}/docker/"
    name: "mintsns-web"
    use_tls: "encrypt"
    state: present

- name: create container
  docker:
    name: mintsns-web-001
    image: mintsns-web
    state: started
    use_tls: "encrypt"
    links:
      - "mintsns-mariadb"
    volumes:
      - "{{ www_dir }}:/var/www/"
    env:
      TERM: "xterm"
      TZ: JST-9
    expose: 80
    ports:
      - 0.0.0.0:8080:8080

- name: create container
  docker:
    name: mintsns-web-002
    image: mintsns-web
    state: started
    use_tls: "encrypt"
    links:
      - "mintsns-mariadb"
    volumes:
      - "{{ www_dir }}:/var/www/"
    env:
      TERM: "xterm"
      TZ: JST-9
    expose: 80
    ports:
      - 0.0.0.0:8080:8080
