---
- name: create container
  docker:
    name: mintsns-web
    image: centos
    state: started
    use_tls: "encrypt"
    tty: yes
    links:
      - "mintsns-mariadb"
    volumes:
      - "{{ www_dir }}:/var/www/"
    env:
      TERM: "xterm"