version: '2'
services:

  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    environment:
        - MODULE=myapp
    depends_on:
      - postgres
      - redis
    volumes:
      - ./web/docker_django:/usr/src/app/docker_django # to Development
      - /usr/src/app/static
    env_file: .env
    command: /usr/local/bin/gunicorn docker_django.wsgi:application -w 2 -b :8000
  
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - ./nginx/static/:/www/static # nginxには static がないため DataVolumeを作成
    volumes_from:
      - web
    depends_on:
      - web

  postgres:
    restart: always
    image: postgres:latest
    volumes_from:
      - data
    ports:
      - "5432:5432"

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"

  data:
    restart: always
    image: postgres:latest
    volumes:
      - ./data/postgresql:/var/lib/postgresql
    command: "true"





